Fix wrong flow
Signed-off-by: Cristian Ariza <dev@cristianrz.com>

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -17,5 +17,8 @@ lxc | "" )
 *) echo invalid option >&2 && exit 1 ;;
 esac
 
-command -v proot >/dev/null 2>&1 || echo 'error: proot is either not installed or not inside PATH' 2>&1 && exit 1
+if ! command -v proot >/dev/null 2>&1; then
+	echo 'error: proot is either not installed or not inside PATH' 2>&1
+	exit 1
+fi
 
